// Code generated by Kitex v0.5.2. DO NOT EDIT.

package viewerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	viewersapi "server/kitex_gen/viewersapi"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Getuniqueviewernames(ctx context.Context, req *viewersapi.Request, callOptions ...callopt.Option) (r *viewersapi.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kViewerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kViewerServiceClient struct {
	*kClient
}

func (p *kViewerServiceClient) Getuniqueviewernames(ctx context.Context, req *viewersapi.Request, callOptions ...callopt.Option) (r *viewersapi.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Getuniqueviewernames(ctx, req)
}
